services:
  - type: web
    name: youpeak-backend
    runtime: node
    rootDir: admin/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5086
      - key: appName
        value: YouPeak
      - key: secretKey
        value: 0LF8bPi5BnOgl3JjLGcfhfU3N7TAk8rJ
      - key: JWT_SECRET
        value: 5BF2AE1515EA6
      - key: EMAIL
        value: youpeak24@gmail.com
      - key: baseURL
        fromService:
          type: web
          name: youpeak-backend
          property: host
      - key: MONGODB_CONNECTION_STRING
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_SECRET_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET
        value: youpeak-videos
      - key: CLOUDFLARE_R2_PUBLIC_DOMAIN
        sync: false
