exports.LOGIN_TYPE = {
  FACEBOOK: 1,
  GOOGLE: 2,
  APPLE: 3,
  EMAIL_PASSWORD: 4,
  ISLOGIN: 5,
};

exports.VIDEO_TYPE = {
  NORMAL_VIDEO: 1,
  SHORT_VIDEO: 2,
};

exports.VISIBILITY_TYPE = {
  PUBLIC: 1,
  PRIVATE: 2,
  UNLISTED: 3,
};

exports.AUDIENCE_TYPE = {
  KIDS: 1,
  ADULTS: 2,
  BOTH: 3,
};

exports.COMMENT_TYPE = {
  ALLOW_ALL: 1,
  DISABLE: 2,
  HOLD_POTENTIALLY_INAPPROPRIATE_FOR_REVIEW: 3,
  HOLD_ALL_FOR_REVIEW: 4,
};

exports.SCHEDULE_TYPE = {
  SCHEDULED: 1,
  NOT_SCHEDULED: 2,
};

exports.PLAYLIST_TYPE = {
  PRIVATE: 1,
  PUBLIC: 2,
};

exports.REPORT_TYPE = {
  SEXUAL: 1,
  VIOLENT_OR_REPULSIVE: 2,
  HATEFUL_OR_ABUSIVE: 3,
  HARMFUL_OR_DANGEROUS: 4,
  SPAM_OR_MISLEADING: 5,
  CHILD_ABUSE: 6,
  OTHERS: 7,
};

exports.WITHDRAWAL_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINE: 3,
};

exports.MONETIZATIONREQUEST_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINE: 3,
};

exports.WALLET_HISTORY_TYPE = {
  EARNING_FROM_MONETIZATION_WITHDRAWAL: 1,
  CONVERTED_COIN_EARNING_FROM_REWARDS_WITHDRAWAL: 2,
};

exports.HISTORY_TYPE = {
  DAILY_CHECK_IN_REWARD: 1,
  EARNING_COIN_FROM_VIEW_AD: 2,
  LOGIN_REWARD: 3,
  REFERRAL_REWARD: 4,
  ENGAGEMENT_WATCHING_VIDEOS_OR_SHORTS_REWARD: 5,
  ENGAGEMENT_COMMENTING_REWARD: 6,
  ENGAGEMENT_LIKING_VIDEOS_OR_SHORTS_REWARD: 7,
  ADD_COIN_COINPLAN_BUY: 8,
  UNLOCK_VIDEO: 9,
  UNLOCK_SUBSCRIPTION: 10,
  PREMIUM_PLAN_BUY: 11,
};

exports.LIVE_TYPE = {
  PUBLIC: 1,
  PRIVATE: 2,
};

exports.CHANNEL_TYPE = {
  PUBLIC: 1,
  PRIVATE: 2,
};

exports.VIDEO_PRIVACY_TYPE = {
  PUBLIC: 1,
  PRIVATE: 2,
};
