// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LefltA4wG0htRi1mJM8rGYIjdNoeqjM',
    appId: '1:554624718564:web:7bf08d15e5d41d53a8fef1',
    messagingSenderId: '554624718564',
    projectId: 'youpeak-9ff65',
    authDomain: 'youpeak-9ff65.firebaseapp.com',
    storageBucket: 'youpeak-9ff65.firebasestorage.app',
    measurementId: 'G-6DBPRR90BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-zboFukcDVSCNThxp6ejEDRXCR_j-ijE',
    appId: '1:554624718564:android:9bd5d288681ec33ba8fef1',
    messagingSenderId: '554624718564',
    projectId: 'youpeak-9ff65',
    storageBucket: 'youpeak-9ff65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTXST0wVkYF0bMVspLgVCYjVYYKJWrMfE',
    appId: '1:554624718564:ios:47e9de7eaf0f4752a8fef1',
    messagingSenderId: '554624718564',
    projectId: 'youpeak-9ff65',
    storageBucket: 'youpeak-9ff65.firebasestorage.app',
    iosBundleId: 'com.live.youpeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTXST0wVkYF0bMVspLgVCYjVYYKJWrMfE',
    appId: '1:554624718564:ios:47ef86ccd4e95e2ba8fef1',
    messagingSenderId: '554624718564',
    projectId: 'youpeak-9ff65',
    storageBucket: 'youpeak-9ff65.firebasestorage.app',
    iosBundleId: 'com.youPeak.live',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3LefltA4wG0htRi1mJM8rGYIjdNoeqjM',
    appId: '1:554624718564:web:e195bc962532193fa8fef1',
    messagingSenderId: '554624718564',
    projectId: 'youpeak-9ff65',
    authDomain: 'youpeak-9ff65.firebaseapp.com',
    storageBucket: 'youpeak-9ff65.firebasestorage.app',
    measurementId: 'G-R6WS4GGHZG',
  );
}
